services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devlink_api_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./:/var/www
    networks:
      - devlink_network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: devlink_api_web
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - devlink_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: devlink_api_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - devlink_db_data:/var/lib/mysql
    networks:
      - devlink_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devlink_api_queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./:/var/www
    networks:
      - devlink_network
    depends_on:
      - db
      - app

networks:
  devlink_network:
    driver: bridge

volumes:
  devlink_db_data:
